# Fayvad Digital - Docker Compose Configuration
name: fayvad_digital

services:
  web:
    build: .

    env_file:
      - .env.prod
      
    restart: unless-stopped
    
    ports:
      - "8003:8000"
      
    volumes:
      - static_volume:/app/staticfiles
      - media_volume:/app/media

    networks:
      - app-network

    extra_hosts:
      - "host.docker.internal:host-gateway"

    command: >
      sh -c "python manage.py migrate && python manage.py collectstatic --noinput && gunicorn fayvad_digital.wsgi:application --bind 0.0.0.0:8000"

volumes:
  static_volume:
  media_volume:

networks:
  app-network:
    driver: bridge