# Generated by Django 5.2.3 on 2025-07-01 05:28

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="AboutPage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(default="About Fayvad Digital", max_length=200),
                ),
                (
                    "subtitle",
                    models.CharField(
                        default="Your trusted partner for digital transformation",
                        max_length=300,
                    ),
                ),
                (
                    "company_story",
                    models.TextField(help_text="Main company story/description"),
                ),
                ("mission", models.TextField(help_text="Company mission statement")),
                ("vision", models.TextField(help_text="Company vision statement")),
                (
                    "values",
                    models.TextField(
                        help_text="Company values (use line breaks for list)"
                    ),
                ),
                (
                    "team_title",
                    models.CharField(default="Our Expert Team", max_length=100),
                ),
                (
                    "team_description",
                    models.TextField(
                        default="Meet the professionals dedicated to your digital success"
                    ),
                ),
                (
                    "services_title",
                    models.CharField(default="What We Do", max_length=100),
                ),
                (
                    "services_description",
                    models.TextField(
                        default="Comprehensive digital solutions for modern businesses"
                    ),
                ),
                (
                    "cta_title",
                    models.CharField(
                        default="Ready to Transform Your Business?", max_length=100
                    ),
                ),
                (
                    "cta_description",
                    models.TextField(
                        default="Let's discuss how we can help you achieve your digital goals"
                    ),
                ),
                ("meta_description", models.CharField(blank=True, max_length=160)),
                ("is_active", models.BooleanField(default=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "About Page Content",
                "verbose_name_plural": "About Page Content",
            },
        ),
        migrations.CreateModel(
            name="HomePage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "hero_title",
                    models.CharField(
                        default="Empowering SMEs & SACCOs with Smart Digital Solutions",
                        max_length=200,
                    ),
                ),
                (
                    "hero_subtitle",
                    models.TextField(
                        default="Transform your business with affordable, professional digital solutions. From websites to ERP systems, we're your trusted technology partner."
                    ),
                ),
                (
                    "hero_cta_text",
                    models.CharField(default="Get Free Consultation", max_length=50),
                ),
                (
                    "hero_secondary_cta",
                    models.CharField(default="View Our Services", max_length=50),
                ),
                ("stat_1_number", models.CharField(default="500+", max_length=20)),
                (
                    "stat_1_label",
                    models.CharField(default="SMEs Digitized", max_length=50),
                ),
                ("stat_2_number", models.CharField(default="50+", max_length=20)),
                (
                    "stat_2_label",
                    models.CharField(default="SACCOs Served", max_length=50),
                ),
                ("stat_3_number", models.CharField(default="98%", max_length=20)),
                (
                    "stat_3_label",
                    models.CharField(default="Client Satisfaction", max_length=50),
                ),
                ("stat_4_number", models.CharField(default="24/7", max_length=20)),
                (
                    "stat_4_label",
                    models.CharField(default="Expert Support", max_length=50),
                ),
                (
                    "about_title",
                    models.CharField(
                        default="Why Choose Fayvad Digital?", max_length=100
                    ),
                ),
                (
                    "about_content",
                    models.TextField(
                        default="We understand that every business is unique. That's why we take a personalized approach, listening carefully, designing solutions that fit your needs, and providing continuous support to ensure you succeed."
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Homepage Content",
                "verbose_name_plural": "Homepage Content",
            },
        ),
        migrations.CreateModel(
            name="TeamMember",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("director", "Director"),
                            ("manager", "Manager"),
                            ("developer", "Developer"),
                            ("designer", "Designer"),
                            ("consultant", "Consultant"),
                            ("support", "Support Specialist"),
                        ],
                        max_length=20,
                    ),
                ),
                ("title", models.CharField(help_text="Job title", max_length=100)),
                ("bio", models.TextField(help_text="Professional biography")),
                ("photo", models.ImageField(blank=True, null=True, upload_to="team/")),
                ("email", models.EmailField(blank=True, max_length=254)),
                ("linkedin", models.URLField(blank=True)),
                (
                    "specializations",
                    models.TextField(
                        blank=True, help_text="Areas of expertise (comma-separated)"
                    ),
                ),
                (
                    "order",
                    models.PositiveIntegerField(default=0, help_text="Display order"),
                ),
                (
                    "is_featured",
                    models.BooleanField(default=True, help_text="Show on about page"),
                ),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "verbose_name": "Team Member",
                "verbose_name_plural": "Team Members",
                "ordering": ["order", "name"],
            },
        ),
    ]
