# Generated by Django 5.2.3 on 2025-07-01 05:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ServiceCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("slug", models.SlugField(unique=True)),
                ("description", models.TextField(blank=True)),
                (
                    "icon",
                    models.CharField(
                        blank=True, help_text="Icon class or emoji", max_length=50
                    ),
                ),
                ("order", models.PositiveIntegerField(default=0)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name_plural": "Service Categories",
                "ordering": ["order", "name"],
            },
        ),
        migrations.CreateModel(
            name="Service",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("slug", models.SlugField(unique=True)),
                (
                    "short_description",
                    models.CharField(
                        help_text="Brief description for cards", max_length=300
                    ),
                ),
                (
                    "description",
                    models.TextField(help_text="Detailed service description"),
                ),
                (
                    "features",
                    models.TextField(help_text="Service features (one per line)"),
                ),
                (
                    "benefits",
                    models.TextField(blank=True, help_text="Key benefits for clients"),
                ),
                (
                    "requirements",
                    models.TextField(
                        blank=True, help_text="What client needs to provide"
                    ),
                ),
                (
                    "process",
                    models.TextField(blank=True, help_text="Our process/methodology"),
                ),
                ("price", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "setup_fee",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                (
                    "billing_cycle",
                    models.CharField(
                        choices=[
                            ("one_time", "One Time"),
                            ("monthly", "Monthly"),
                            ("yearly", "Yearly"),
                            ("quarterly", "Quarterly"),
                        ],
                        default="one_time",
                        max_length=20,
                    ),
                ),
                ("order", models.PositiveIntegerField(default=0)),
                (
                    "is_featured",
                    models.BooleanField(
                        default=False, help_text="Show in featured section"
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("meta_description", models.CharField(blank=True, max_length=160)),
                ("meta_keywords", models.CharField(blank=True, max_length=200)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="services.servicecategory",
                    ),
                ),
            ],
            options={
                "ordering": ["order", "name"],
            },
        ),
    ]
