# Generated by Django 5.2.3 on 2025-07-01 05:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="PortfolioCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("slug", models.SlugField(unique=True)),
                ("description", models.TextField(blank=True)),
                ("order", models.PositiveIntegerField(default=0)),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "verbose_name_plural": "Portfolio Categories",
                "ordering": ["order", "name"],
            },
        ),
        migrations.CreateModel(
            name="Portfolio",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("slug", models.SlugField(unique=True)),
                ("client_name", models.CharField(max_length=100)),
                (
                    "client_logo",
                    models.ImageField(
                        blank=True, null=True, upload_to="portfolio/logos/"
                    ),
                ),
                (
                    "service_type",
                    models.CharField(
                        choices=[
                            ("website", "Website Development"),
                            ("odoo", "Odoo ERP"),
                            ("zoho", "Zoho Solutions"),
                            ("crm", "CRM Implementation"),
                            ("hosting", "Hosting & Domain"),
                            ("ecommerce", "E-commerce"),
                            ("custom", "Custom Development"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "short_description",
                    models.CharField(
                        help_text="Brief description for cards/previews", max_length=300
                    ),
                ),
                (
                    "description",
                    models.TextField(help_text="Detailed project description"),
                ),
                (
                    "challenge",
                    models.TextField(
                        blank=True, help_text="What challenge did this project solve?"
                    ),
                ),
                (
                    "solution",
                    models.TextField(blank=True, help_text="How did we solve it?"),
                ),
                (
                    "results",
                    models.TextField(
                        blank=True, help_text="What were the outcomes/results?"
                    ),
                ),
                ("featured_image", models.ImageField(upload_to="portfolio/featured/")),
                (
                    "gallery_images",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="List of additional image URLs",
                    ),
                ),
                (
                    "project_url",
                    models.URLField(blank=True, help_text="Live project URL"),
                ),
                (
                    "demo_url",
                    models.URLField(blank=True, help_text="Demo or staging URL"),
                ),
                ("completion_date", models.DateField()),
                (
                    "duration_months",
                    models.PositiveIntegerField(help_text="Project duration in months"),
                ),
                (
                    "project_cost",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                (
                    "client_testimonial",
                    models.TextField(blank=True, help_text="Client testimonial/quote"),
                ),
                (
                    "client_rating",
                    models.PositiveIntegerField(
                        blank=True,
                        choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)],
                        null=True,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("completed", "Completed"),
                            ("ongoing", "Ongoing"),
                            ("maintenance", "Under Maintenance"),
                        ],
                        default="completed",
                        max_length=20,
                    ),
                ),
                (
                    "featured",
                    models.BooleanField(default=False, help_text="Show on homepage"),
                ),
                ("show_in_portfolio", models.BooleanField(default=True)),
                (
                    "technologies_used",
                    models.JSONField(
                        default=list, help_text="List of technologies/tools used"
                    ),
                ),
                ("meta_description", models.CharField(blank=True, max_length=160)),
                ("meta_keywords", models.CharField(blank=True, max_length=200)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="portfolio_items",
                        to="portfolio.portfoliocategory",
                    ),
                ),
            ],
            options={
                "verbose_name": "Portfolio Item",
                "verbose_name_plural": "Portfolio Items",
                "ordering": ["-featured", "-completion_date"],
            },
        ),
    ]
